# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        font = QFont()
        font.setFamily(u"\u9ed1\u4f53")
        font.setPointSize(15)
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.icon = QLabel(self.centralwidget)
        self.icon.setObjectName(u"icon")
        self.icon.setGeometry(QRect(0, 0, 150, 150))
        self.icon.setMinimumSize(QSize(0, 0))
        self.icon.setMaximumSize(QSize(9999999, 9999999))
        self.icon.setPixmap(QPixmap(u"img/IMAGE_iP2SjlZhb_1690890042506.png"))
        self.icon.setScaledContents(True)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(200, 30, 400, 50))
        font1 = QFont()
        font1.setFamily(u"YEFONTJingHongXingKai")
        font1.setPointSize(35)
        self.label_2.setFont(font1)
        self.icon2 = QLabel(self.centralwidget)
        self.icon2.setObjectName(u"icon2")
        self.icon2.setGeometry(QRect(650, 0, 150, 150))
        self.icon2.setPixmap(QPixmap(u"img/out.png"))
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 150, 800, 5))
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        font2 = QFont()
        font2.setFamily(u"YEFONTJingHongXingKai \u6a19\u6e96")
        font2.setPointSize(1)
        self.line.setFont(font2)
        self.line.setLineWidth(3)
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(0, 150, 5, 385))
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(0, 535, 800, 5))
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setFont(font2)
        self.line_3.setLayoutDirection(Qt.RightToLeft)
        self.line_3.setLineWidth(3)
        self.line_3.setMidLineWidth(0)
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.line_4 = QFrame(self.centralwidget)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(799, 150, 5, 385))
        self.line_4.setLayoutDirection(Qt.LeftToRight)
        self.line_4.setAutoFillBackground(False)
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QFrame.VLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.horizontalLayoutWidget = QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(190, 100, 411, 31))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.agreement = QCheckBox(self.horizontalLayoutWidget)
        self.agreement.setObjectName(u"agreement")
        font3 = QFont()
        font3.setFamily(u"\u9ed1\u4f53")
        font3.setPointSize(12)
        self.agreement.setFont(font3)

        self.horizontalLayout.addWidget(self.agreement)

        self.pb_am = QPushButton(self.horizontalLayoutWidget)
        self.pb_am.setObjectName(u"pb_am")
        self.pb_am.setFont(font3)

        self.horizontalLayout.addWidget(self.pb_am)

        self.label = QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName(u"label")
        self.label.setFont(font3)

        self.horizontalLayout.addWidget(self.label)

        self.pb_sm = QPushButton(self.horizontalLayoutWidget)
        self.pb_sm.setObjectName(u"pb_sm")
        self.pb_sm.setFont(font3)

        self.horizontalLayout.addWidget(self.pb_sm)

        self.line_5 = QFrame(self.centralwidget)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(400, 150, 3, 385))
        self.line_5.setFrameShape(QFrame.VLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(420, 160, 60, 30))
        font4 = QFont()
        font4.setFamily(u"YEFONTJingHongXingKai")
        font4.setPointSize(15)
        self.label_3.setFont(font4)
        font11=QFont()
        font11.setFamily(u"YEFONTJingHongXingKai")
        font11.setPointSize(10)
        self.search_keyword = QLineEdit(self.centralwidget)
        self.search_keyword.setFont(font11)
        self.search_keyword.setObjectName(u"search_keyword")
        self.search_keyword.setGeometry(QRect(480, 160, 150, 30))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(650, 160, 60, 30))
        self.label_4.setFont(font4)
        self.search_num = QSpinBox(self.centralwidget)
        self.search_num.setObjectName(u"search_num")
        self.search_num.setGeometry(QRect(710, 160, 60, 30))
        font5 = QFont()
        font5.setFamily(u"Ink Free")
        font5.setPointSize(15)
        self.search_num.setFont(font5)
        self.search_num.setMinimum(10)
        self.search_num.setMaximum(150)
        self.search_num.setSingleStep(5)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(420, 200, 60, 30))
        font6 = QFont()
        font6.setFamily(u"YEFONTJingHongXingKai")
        font6.setPointSize(10)
        self.label_5.setFont(font6)
        self.search = QPushButton(self.centralwidget)
        self.search.setObjectName(u"search")
        self.search.setGeometry(QRect(690, 200, 80, 25))
        self.search.setFont(font4)
        self.hot1 = QPushButton(self.centralwidget)
        self.hot1.setObjectName(u"hot1")
        self.hot1.setGeometry(QRect(480, 205, 35, 21))
        font7 = QFont()
        font7.setFamily(u"\u4eff\u5b8b")
        font7.setPointSize(7)
        self.hot1.setFont(font7)
        self.hot2 = QPushButton(self.centralwidget)
        self.hot2.setObjectName(u"hot2")
        self.hot2.setGeometry(QRect(520, 205, 35, 21))
        self.hot2.setFont(font7)
        self.hot4 = QPushButton(self.centralwidget)
        self.hot4.setObjectName(u"hot4")
        self.hot4.setGeometry(QRect(600, 205, 35, 20))
        self.hot4.setFont(font7)
        self.hot5 = QPushButton(self.centralwidget)
        self.hot5.setObjectName(u"hot5")
        self.hot5.setGeometry(QRect(640, 205, 35, 20))
        self.hot5.setFont(font7)
        self.hot3 = QPushButton(self.centralwidget)
        self.hot3.setObjectName(u"hot3")
        self.hot3.setGeometry(QRect(560, 205, 35, 21))
        self.hot3.setFont(font7)
        self.line_6 = QFrame(self.centralwidget)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(400, 230, 400, 3))
        self.line_6.setFrameShape(QFrame.HLine)
        self.line_6.setFrameShadow(QFrame.Sunken)
        self.search_list = QListWidget(self.centralwidget)
        self.search_list.setObjectName(u"search_list")
        self.search_list.setGeometry(QRect(420, 250, 360, 180))
        font8 = QFont()
        font8.setFamily(u"Ink Free")
        font8.setPointSize(10)
        self.search_list.setFont(font8)
        self.search_choose = QLabel(self.centralwidget)
        self.search_choose.setObjectName(u"search_choose")
        self.search_choose.setGeometry(QRect(420, 440, 360, 15))
        self.search_choose.setFont(font6)
        self.pdf_browser = QPushButton(self.centralwidget)
        self.pdf_browser.setObjectName(u"pdf_browser")
        self.pdf_browser.setGeometry(QRect(420, 460, 150, 25))
        font9 = QFont()
        font9.setFamily(u"YEFONTJingHongXingKai")
        font9.setPointSize(12)
        self.pdf_browser.setFont(font9)
        self.pdf_url = QPushButton(self.centralwidget)
        self.pdf_url.setObjectName(u"pdf_url")
        self.pdf_url.setGeometry(QRect(585, 460, 80, 25))
        self.pdf_url.setFont(font9)
        self.phone_pdf = QPushButton(self.centralwidget)
        self.phone_pdf.setObjectName(u"phone_pdf")
        self.phone_pdf.setGeometry(QRect(680, 460, 100, 25))
        self.phone_pdf.setFont(font9)
        self.browser_pan = QPushButton(self.centralwidget)
        self.browser_pan.setObjectName(u"browser_pan")
        self.browser_pan.setGeometry(QRect(420, 500, 160, 25))
        self.browser_pan.setFont(font9)
        self.phone_pan = QPushButton(self.centralwidget)
        self.phone_pan.setObjectName(u"phone_pan")
        self.phone_pan.setGeometry(QRect(600, 500, 180, 25))
        self.phone_pan.setFont(font9)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 545, 150, 25))
        self.label_7.setFont(font5)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(180, 545, 150, 25))
        self.label_8.setFont(font5)
        self.developer = QPushButton(self.centralwidget)
        self.developer.setObjectName(u"developer")
        self.developer.setGeometry(QRect(525, 545, 120, 25))
        font10 = QFont()
        font10.setFamily(u"Ink Free")
        font10.setPointSize(12)
        self.developer.setFont(font10)
        self.setting = QPushButton(self.centralwidget)
        self.setting.setObjectName(u"setting")
        self.setting.setGeometry(QRect(660, 545, 120, 25))
        self.setting.setFont(font10)
        self.github = QPushButton(self.centralwidget)
        self.github.setObjectName(u"github")
        self.github.setGeometry(QRect(429, 545, 80, 25))
        self.github.setFont(font5)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 160, 50, 30))
        self.label_9.setFont(font4)
        self.get_tp = QComboBox(self.centralwidget)
        self.get_tp.addItem("")
        #self.get_tp.addItem("")
        #self.get_tp.addItem("")
        #self.get_tp.addItem("")
        self.get_tp.setObjectName(u"get_tp")
        self.get_tp.setGeometry(QRect(70, 160, 120, 30))
        self.get_tp.setFont(font4)
        self.get_grade = QComboBox(self.centralwidget)
        self.get_grade.addItem("")
        self.get_grade.addItem("")
        self.get_grade.addItem("")
        self.get_grade.addItem("")
        self.get_grade.addItem("")
        self.get_grade.addItem("")
        self.get_grade.addItem("")
        self.get_grade.addItem("")
        self.get_grade.addItem("")
        self.get_grade.addItem("")
        self.get_grade.addItem("")
        self.get_grade.addItem("")
        self.get_grade.setObjectName(u"get_grade")
        self.get_grade.setGeometry(QRect(200, 160, 90, 30))
        self.get_grade.setFont(font4)
        self.get_subject = QComboBox(self.centralwidget)
        self.get_subject.addItem("")
        self.get_subject.addItem("")
        self.get_subject.addItem("")
        self.get_subject.addItem("")
        self.get_subject.addItem("")
        self.get_subject.addItem("")
        self.get_subject.addItem("")
        self.get_subject.addItem("")
        self.get_subject.addItem("")
        self.get_subject.setObjectName(u"get_subject")
        self.get_subject.setGeometry(QRect(300, 160, 80, 30))
        self.get_subject.setFont(font4)
        self.get = QPushButton(self.centralwidget)
        self.get.setObjectName(u"get")
        self.get.setGeometry(QRect(20, 200, 360, 30))
        self.get.setFont(font4)
        self.get_list = QListWidget(self.centralwidget)
        self.get_list.setObjectName(u"get_list")
        self.get_list.setGeometry(QRect(20, 250, 360, 180))
        self.get_list.setFont(font8)
        self.get_choose = QLabel(self.centralwidget)
        self.get_choose.setObjectName(u"get_choose")
        self.get_choose.setGeometry(QRect(20, 440, 360, 15))
        self.get_choose.setFont(font6)
        self.get_browser = QPushButton(self.centralwidget)
        self.get_browser.setObjectName(u"get_browser")
        self.get_browser.setGeometry(QRect(20, 460, 150, 25))
        self.get_browser.setFont(font9)
        self.get_url = QPushButton(self.centralwidget)
        self.get_url.setObjectName(u"get_url")
        self.get_url.setGeometry(QRect(185, 460, 80, 25))
        self.get_url.setFont(font9)
        self.get_phone = QPushButton(self.centralwidget)
        self.get_phone.setObjectName(u"get_phone")
        self.get_phone.setGeometry(QRect(280, 460, 100, 25))
        self.get_phone.setFont(font9)
        self.get_browser_pan = QPushButton(self.centralwidget)
        self.get_browser_pan.setObjectName(u"get_browser_pan")
        self.get_browser_pan.setGeometry(QRect(20, 500, 160, 25))
        self.get_browser_pan.setFont(font9)
        self.get_phone_pan = QPushButton(self.centralwidget)
        self.get_phone_pan.setObjectName(u"get_phone_pan")
        self.get_phone_pan.setGeometry(QRect(200, 500, 180, 25))
        self.get_phone_pan.setFont(font9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setFont(font9)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setContextMenuPolicy(Qt.DefaultContextMenu)
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.icon.setText("")
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u5317\u4eac\u9898\u5e93\u62d3\u5c55\u7a0b\u5e8f", None))
        self.icon2.setText("")
        self.agreement.setText(QCoreApplication.translate("MainWindow", u"\u6211\u5df2\u9605\u8bfb\u5e76\u540c\u610f", None))
        self.pb_am.setText(QCoreApplication.translate("MainWindow", u"\u7528\u6237\u534f\u8bae", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u4e14\u77e5\u6653\u5e76\u8ba4\u540c", None))
        self.pb_sm.setText(QCoreApplication.translate("MainWindow", u"\u58f0\u660e", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u641c\u7d22\uff1a", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u6570\u91cf\uff1a", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u731c\u4f60\u60f3\u641c\uff1a", None))
        self.search.setText(QCoreApplication.translate("MainWindow", u"\u641c\u7d22", None))
        self.hot1.setText(QCoreApplication.translate("MainWindow", u"2022", None))
        self.hot2.setText(QCoreApplication.translate("MainWindow", u"\u8bed\u6587\u6570\u5b66", None))
        self.hot4.setText(QCoreApplication.translate("MainWindow", u"2022", None))
        self.hot5.setText(QCoreApplication.translate("MainWindow", u"\u6708\u8003", None))
        self.hot3.setText(QCoreApplication.translate("MainWindow", u"\u82f1\u8bed", None))
        self.search_choose.setText("")
        self.pdf_browser.setText(QCoreApplication.translate("MainWindow", u"\u9ed8\u8ba4\u6d4f\u89c8\u5668\u6253\u5f00", None))
        self.pdf_url.setText(QCoreApplication.translate("MainWindow", u"\u590d\u5236URL", None))
        self.phone_pdf.setText(QCoreApplication.translate("MainWindow", u"\u624b\u673a\u626b\u7801\u4e0b\u8f7d", None))
        self.browser_pan.setText(QCoreApplication.translate("MainWindow", u"\u6d4f\u89c8\u5668\u8df3\u8f6c\u767e\u5ea6\u7f51\u76d8", None))
        self.phone_pan.setText(QCoreApplication.translate("MainWindow", u"\u624b\u673a\u767e\u5ea6\u7f51\u76d8\u626b\u7801\u83b7\u53d6", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Version\uff1a1.0", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Sun Sep 10 2023", None))
        self.developer.setText(QCoreApplication.translate("MainWindow", u"\u8054\u7cfb\u5f00\u53d1\u8005", None))
        self.setting.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e", None))
        self.github.setText(QCoreApplication.translate("MainWindow", u"github", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u83b7\u53d6\uff1a", None))
        self.get_tp.setItemText(0, QCoreApplication.translate("MainWindow", u"\u70ed\u699c", None))
        #self.get_tp.setItemText(1, QCoreApplication.translate("MainWindow", u"\u7535\u5b50\u8bfe\u672c", None))
        #self.get_tp.setItemText(2, QCoreApplication.translate("MainWindow", u"\u4e2d\u8003\u771f\u9898", None))
        #self.get_tp.setItemText(3, QCoreApplication.translate("MainWindow", u"\u9ad8\u8003\u771f\u9898", None))

        self.get_grade.setItemText(0, QCoreApplication.translate("MainWindow", u"\u4e00\u5e74\u7ea7", None))
        self.get_grade.setItemText(1, QCoreApplication.translate("MainWindow", u"\u4e8c\u5e74\u7ea7", None))
        self.get_grade.setItemText(2, QCoreApplication.translate("MainWindow", u"\u4e09\u5e74\u7ea7", None))
        self.get_grade.setItemText(3, QCoreApplication.translate("MainWindow", u"\u56db\u5e74\u7ea7", None))
        self.get_grade.setItemText(4, QCoreApplication.translate("MainWindow", u"\u4e94\u5e74\u7ea7", None))
        self.get_grade.setItemText(5, QCoreApplication.translate("MainWindow", u"\u516d\u5e74\u7ea7", None))
        self.get_grade.setItemText(6, QCoreApplication.translate("MainWindow", u"\u521d\u4e00", None))
        self.get_grade.setItemText(7, QCoreApplication.translate("MainWindow", u"\u521d\u4e8c", None))
        self.get_grade.setItemText(8, QCoreApplication.translate("MainWindow", u"\u521d\u4e09", None))
        self.get_grade.setItemText(9, QCoreApplication.translate("MainWindow", u"\u9ad8\u4e00", None))
        self.get_grade.setItemText(10, QCoreApplication.translate("MainWindow", u"\u9ad8\u4e8c", None))
        self.get_grade.setItemText(11, QCoreApplication.translate("MainWindow", u"\u9ad8\u4e09", None))

        self.get_subject.setItemText(0, QCoreApplication.translate("MainWindow", u"\u8bed\u6587", None))
        self.get_subject.setItemText(1, QCoreApplication.translate("MainWindow", u"\u6570\u5b66", None))
        self.get_subject.setItemText(2, QCoreApplication.translate("MainWindow", u"\u82f1\u8bed", None))
        self.get_subject.setItemText(3, QCoreApplication.translate("MainWindow", u"\u5386\u53f2", None))
        self.get_subject.setItemText(4, QCoreApplication.translate("MainWindow", u"\u5730\u7406", None))
        self.get_subject.setItemText(5, QCoreApplication.translate("MainWindow", u"\u751f\u7269", None))
        self.get_subject.setItemText(6, QCoreApplication.translate("MainWindow", u"\u653f\u6cbb", None))
        self.get_subject.setItemText(7, QCoreApplication.translate("MainWindow", u"\u7269\u7406", None))
        self.get_subject.setItemText(8, QCoreApplication.translate("MainWindow", u"\u5316\u5b66", None))

        self.get.setText(QCoreApplication.translate("MainWindow", u"\u70b9\u51fb\u83b7\u53d6", None))
        self.get_choose.setText("")
        self.get_browser.setText(QCoreApplication.translate("MainWindow", u"\u9ed8\u8ba4\u6d4f\u89c8\u5668\u6253\u5f00", None))
        self.get_url.setText(QCoreApplication.translate("MainWindow", u"\u590d\u5236URL", None))
        self.get_phone.setText(QCoreApplication.translate("MainWindow", u"\u624b\u673a\u626b\u7801\u4e0b\u8f7d", None))
        self.get_browser_pan.setText(QCoreApplication.translate("MainWindow", u"\u6d4f\u89c8\u5668\u8df3\u8f6c\u767e\u5ea6\u7f51\u76d8", None))
        self.get_phone_pan.setText(QCoreApplication.translate("MainWindow", u"\u624b\u673a\u767e\u5ea6\u7f51\u76d8\u626b\u7801\u83b7\u53d6", None))
    # retranslateUi

